--drop table tbl_application_properties;
--drop table tbl_auth_management_properties;
--drop table KAVACH_OTP_LOGS;
--drop table TBL_EVENT_ENTITY;
--drop table TBL_PASSWORD_HISTORY;
--drop table TBL_ROLE_API_ACCESS_MAPPING;
--
--
--drop SEQUENCE OTL_SYS_ID;
--drop SEQUENCE SEQ_API_ID;
--drop SEQUENCE SEQ_EVENT_ENTITY;
--drop SEQUENCE SEQ_OFFICELOCID;
--drop SEQUENCE SEQ_ROLE_ID;
--
--drop table TBL_USER_ROLE_MAPPING;
--drop table TBL_USER_M;
--drop table TBL_REGIONAL_OFFICE_M;
--drop table TBL_OFFCLOCATION_M;
--drop table TBL_ROLE_M;
--drop table SMS_GENERATION_LOGS;
--drop table TBL_API_M;
--drop table SMS_TOKEN;
--drop table SMS_TOKEN_GENERATION_LOGS;
--drop table TBL_TOKEN;
--drop table TBL_APPROVAL_FLOW;


CREATE SEQUENCE OTL_SYS_ID;
CREATE SEQUENCE SEQ_API_ID;
CREATE SEQUENCE SEQ_EVENT_ENTITY;
CREATE SEQUENCE SEQ_OFFICELOCID;
CREATE SEQUENCE SEQ_ROLE_ID;

CREATE TABLE "TBL_APPLICATION_PROPERTIES"(
"S_KEY" VARCHAR2(1000 BYTE) NOT NULL ENABLE,
"S_VALUE" VARCHAR2(1000 BYTE),UNIQUE ("S_KEY")
);

CREATE TABLE "TBL_AUTH_MANAGEMENT_PROPERTIES"(
"S_KEY" VARCHAR2(1000 BYTE) NOT NULL ENABLE,
"S_VALUE" VARCHAR2(2000 BYTE)
);

CREATE TABLE "TBL_API_M"(
"N_API_ID" NUMBER NOT NULL ENABLE,
"S_URI" VARCHAR2(1000 CHAR) NOT NULL ENABLE,
"S_METHOD" VARCHAR2(100 CHAR),
"N_IS_ACTIVE" NUMBER(1,0) DEFAULT ON NULL 1 NOT NULL ENABLE,
"DT_CREATED_ON" DATE DEFAULT ON NULL SYSDATE NOT NULL ENABLE, 	
"S_CREATED_BY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 	
"DT_UPDATED_ON" DATE, 	
"S_UPDATED_BY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 	
"N_IS_PUBLIC" NUMBER(1,0) DEFAULT ON NULL 0 NOT NULL ENABLE
);

CREATE UNIQUE INDEX "TBL_API_M_PK" ON "TBL_API_M" ("N_API_ID");
ALTER TABLE "TBL_API_M" ADD CONSTRAINT "TBL_API_M_PK" PRIMARY KEY ("N_API_ID") USING INDEX "TBL_API_M_PK"  ENABLE;

CREATE TABLE "KAVACH_OTP_LOGS" (
"OTL_SYS_ID" NUMBER, 	
"OTL_TOKEN" VARCHAR2(300 BYTE), 	
"OTL_OTP" VARCHAR2(6 BYTE), 	
"OTL_MOBILE_NUMBER" NUMBER(10,0), 	
"OTL_KEY" VARCHAR2(500 BYTE)
);


CREATE TABLE "TBL_EVENT_ENTITY"(
"N_EVENT_ID" NUMBER,
"S_LEVEL" VARCHAR2(4000 CHAR),
"DT_EVENTDATE" TIMESTAMP (6),
"S_MESSAGE" VARCHAR2(4000 CHAR),
"S_LOGGER" VARCHAR2(4000 CHAR),
"S_TYPE" VARCHAR2(100 CHAR),
"S_USER_ID" VARCHAR2(4000 CHAR),
"S_IP_ADDRESS" VARCHAR2(100 CHAR),
"S_JSON_REQUEST" VARCHAR2(4000 CHAR),
"S_APPLICATION_NAME" VARCHAR2(200 CHAR)
);

CREATE UNIQUE INDEX "TBL_EVENT_ENTITY_PK" ON "TBL_EVENT_ENTITY" ("N_EVENT_ID");
ALTER TABLE "TBL_EVENT_ENTITY" ADD CONSTRAINT "TBL_EVENT_ENTITY_PK" PRIMARY KEY ("N_EVENT_ID")  USING INDEX "TBL_EVENT_ENTITY_PK"  ENABLE;

CREATE TABLE "TBL_OFFCLOCATION_M"(
"N_OFFCLOCID" NUMBER(10,0),
"S_LOCATIONSN" VARCHAR2(30 CHAR), 	
"S_LOCATIONLN" VARCHAR2(50 CHAR), 
"N_STATUS" NUMBER(1,0), 	
"S_CREATEDBY" VARCHAR2(50 CHAR), 	
"DT_CREATEDDATE" DATE, 	
"S_UPDATEDBY" VARCHAR2(50 CHAR), 	
"DT_UPDATEDDATE" DATE) ;

CREATE UNIQUE INDEX "TBL_OFFCLOCATION_M_PK" ON "TBL_OFFCLOCATION_M" ("N_OFFCLOCID");
ALTER TABLE "TBL_OFFCLOCATION_M" MODIFY ("N_OFFCLOCID" NOT NULL ENABLE);
ALTER TABLE "TBL_OFFCLOCATION_M" MODIFY ("S_LOCATIONSN" NOT NULL ENABLE);
ALTER TABLE "TBL_OFFCLOCATION_M" MODIFY ("S_LOCATIONLN" NOT NULL ENABLE);
ALTER TABLE "TBL_OFFCLOCATION_M" MODIFY ("N_STATUS" NOT NULL ENABLE);
ALTER TABLE "TBL_OFFCLOCATION_M" ADD CONSTRAINT "TBL_OFFCLOCATION_M_PK" PRIMARY KEY ("N_OFFCLOCID")USING INDEX "TBL_OFFCLOCATION_M_PK"  ENABLE;


CREATE TABLE "TBL_REGIONAL_OFFICE_M"(
"S_ROCODE" VARCHAR2(3), 	
"S_RONAME" VARCHAR2(100), 	
"S_CREATEDBY" VARCHAR2(50 CHAR), 	
"DT_CREATEDDATE" DATE, 	
"S_UPDATEDBY" VARCHAR2(50 CHAR), 	
"DT_UPDATEDDATE" DATE) ;

CREATE UNIQUE INDEX "TBL_REGIONAL_OFFICE_M_PK" ON "TBL_REGIONAL_OFFICE_M" ("S_ROCODE");
ALTER TABLE "TBL_REGIONAL_OFFICE_M" ADD CONSTRAINT "TBL_REGIONAL_OFFICE_M_PK" PRIMARY KEY ("S_ROCODE")  USING INDEX "TBL_REGIONAL_OFFICE_M_PK"  ENABLE; 


CREATE TABLE "TBL_USER_M"(
"N_USERID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 	
"S_USEREMAILID" VARCHAR2(50 CHAR), 	
"S_USERNAME" VARCHAR2(50 CHAR), 	
"S_FIRSTNAME" VARCHAR2(100 CHAR), 	
"S_LASTNAME" VARCHAR2(100 CHAR), 	
"S_ROCODE" VARCHAR2(3), 	
"N_OFFCLOCID" NUMBER(10,0), 	
"N_USERMOBNO" VARCHAR2(30), 	
"N_STATUS" NUMBER(1,0), 	
"S_CREATEDBY" VARCHAR2(255 CHAR), 	
"DT_CREATEDDATE" DATE, 	
"S_UPDATEDBY" VARCHAR2(255 CHAR), 	
"DT_UPDATEDDATE" DATE, 	"S_PASSWORD" VARCHAR2(1024), 	
"N_ISLDAPUSER" NUMBER(1,0), 	
"N_UNSUCCESS_ATTEMPT" NUMBER(2,0) DEFAULT ON NULL 0, 	
"DT_BLOCK_TILL" DATE, 	
"DT_PASS_EXPIRED" DATE, 	
"DT_LAST_ATTEMPT" DATE, 	
"DT_LAST_FAILED_ATTEMPT" TIMESTAMP (6), 
"DT_LASTLOGINDATE" DATE
) ;

CREATE UNIQUE INDEX "TBL_USER_M_PK" ON "TBL_USER_M" ("N_USERID");
ALTER TABLE "TBL_USER_M" MODIFY ("S_USEREMAILID" NOT NULL ENABLE);
ALTER TABLE "TBL_USER_M" MODIFY ("S_USERNAME" NOT NULL ENABLE);
ALTER TABLE "TBL_USER_M" MODIFY ("N_STATUS" NOT NULL ENABLE);
ALTER TABLE "TBL_USER_M" ADD CONSTRAINT "TBL_USER_M_PK" PRIMARY KEY ("N_USERID")  USING INDEX "TBL_USER_M_PK"  ENABLE;
ALTER TABLE "TBL_USER_M" MODIFY ("N_ISLDAPUSER" NOT NULL ENABLE);
ALTER TABLE "TBL_USER_M" ADD CONSTRAINT "TBL_USER_M_FK1" FOREIGN KEY ("S_ROCODE")	  REFERENCES "TBL_REGIONAL_OFFICE_M" ("S_ROCODE") ENABLE;
ALTER TABLE "TBL_USER_M" ADD CONSTRAINT "TBL_USER_M_FK2" FOREIGN KEY ("N_OFFCLOCID")	  REFERENCES "TBL_OFFCLOCATION_M" ("N_OFFCLOCID") ENABLE;

CREATE TABLE "TBL_PASSWORD_HISTORY"("N_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
"N_USERID" NUMBER, 	
"S_PASSWORD" VARCHAR2(1000), 	
"S_CREATED_ON" DATE DEFAULT ON NULL SYSDATE, 	
"S_CREATED_BY" VARCHAR2(100)
) ;

CREATE UNIQUE INDEX "TBL_PASSWORD_HISTORY_PK" ON "TBL_PASSWORD_HISTORY" ("N_ID");
ALTER TABLE "TBL_PASSWORD_HISTORY" ADD CONSTRAINT "TBL_PASSWORD_HISTORY_PK" PRIMARY KEY ("N_ID")  USING INDEX "TBL_PASSWORD_HISTORY_PK"  ENABLE;
ALTER TABLE "TBL_PASSWORD_HISTORY" ADD CONSTRAINT "TBL_PASSWORD_HISTORY_FK" FOREIGN KEY ("N_USERID")	  REFERENCES "TBL_USER_M" ("N_USERID") ENABLE;


CREATE TABLE "TBL_ROLE_M"(
"N_ROLEID" NUMBER(10,0), 	
"S_ROLENAME" VARCHAR2(30 CHAR), 	
"N_STATUS" NUMBER(1,0), 	
"S_CREATEDBY" VARCHAR2(50 CHAR), 	
"DT_CREATEDDATE" DATE, 	
"S_UPDATEDBY" VARCHAR2(50 CHAR), 	
"DT_UPDATEDDATE" DATE
);


CREATE UNIQUE INDEX "TBL_ROLE_M_PK" ON "TBL_ROLE_M" ("N_ROLEID")   ;
ALTER TABLE "TBL_ROLE_M" MODIFY ("S_ROLENAME" NOT NULL ENABLE);
ALTER TABLE "TBL_ROLE_M" MODIFY ("N_STATUS" NOT NULL ENABLE);
ALTER TABLE "TBL_ROLE_M" ADD CONSTRAINT "TBL_ROLE_M_PK" PRIMARY KEY ("N_ROLEID")  USING INDEX "TBL_ROLE_M_PK"  ENABLE;


CREATE TABLE "TBL_USER_ROLE_MAPPING"(
"N_USERID" NUMBER, 	
"N_ROLEID" NUMBER(10,0)
) ;

ALTER TABLE "TBL_USER_ROLE_MAPPING" ADD CONSTRAINT "TBL_USER_ROLE_MAPPING_FK1" FOREIGN KEY ("N_ROLEID")	  REFERENCES "TBL_ROLE_M" ("N_ROLEID") ENABLE;
ALTER TABLE "TBL_USER_ROLE_MAPPING" ADD CONSTRAINT "TBL_USER_ROLE_MAPPING_FK2" FOREIGN KEY ("N_USERID")	  REFERENCES "TBL_USER_M" ("N_USERID") ENABLE;


CREATE TABLE "TBL_ROLE_API_ACCESS_MAPPING"(	
"N_MAPPING_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 	
"S_API_ID" NUMBER, 	
"N_ROLEID" NUMBER, 	
"DT_CREATED_ON" DATE DEFAULT ON NULL SYSDATE, 	
"DT_UPDATED_ON" DATE
) ;

CREATE UNIQUE INDEX "TBL_ROLE_API_ACCESS_MAPPING_PK" ON "TBL_ROLE_API_ACCESS_MAPPING" ("N_MAPPING_ID")   ;
ALTER TABLE "TBL_ROLE_API_ACCESS_MAPPING" ADD CONSTRAINT "TBL_ROLE_API_ACCESS_MAPPING_PK" PRIMARY KEY ("N_MAPPING_ID")USING INDEX "TBL_ROLE_API_ACCESS_MAPPING_PK"  ENABLE;
ALTER TABLE "TBL_ROLE_API_ACCESS_MAPPING" ADD CONSTRAINT "TBL_ROLE_API_ACCESS_MAPPING_FK1" FOREIGN KEY ("S_API_ID")	  REFERENCES "TBL_API_M" ("N_API_ID") ENABLE;
ALTER TABLE "TBL_ROLE_API_ACCESS_MAPPING" ADD CONSTRAINT "TBL_ROLE_API_ACCESS_MAPPING_FK2" FOREIGN KEY ("N_ROLEID")	  REFERENCES "TBL_ROLE_M" ("N_ROLEID") ENABLE;


CREATE TABLE "SMS_GENERATION_LOGS"(	
"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 	
"MOBILE_NO" VARCHAR2(500), 	
"TEXT" VARCHAR2(4000), 	
"STATUS" NUMBER(1,0), 	
"SENT_ON" TIMESTAMP (6)
) ;


CREATE TABLE "SMS_TOKEN"(
"VALUE" VARCHAR2(500), 	
"EXPIRY_DATE" TIMESTAMP (6)
) ;


CREATE UNIQUE INDEX "SYS_C00121627" ON "SMS_TOKEN" ("VALUE");
ALTER TABLE "SMS_TOKEN" ADD PRIMARY KEY ("VALUE")  USING INDEX  ENABLE; 


CREATE TABLE "SMS_TOKEN_GENERATION_LOGS"(	
"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 	
"ATTEMPT_DATE" TIMESTAMP (6), 	
"STATUS" NUMBER(1,0)
) ;

CREATE TABLE "TBL_TOKEN"(	
"N_REFRESHTOKENID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 	
"S_USERNAME" VARCHAR2(100 CHAR), 	
"S_TOKEN" VARCHAR2(100 CHAR), 	
"S_TYPE" VARCHAR2(100 CHAR), 	
"DT_CREATEDDATE" TIMESTAMP (6), 	
"DT_EXPIRATIONDATE" TIMESTAMP (6)
) ;

CREATE UNIQUE INDEX "TBL_TOKEN_PK" ON "TBL_TOKEN" ("N_REFRESHTOKENID");
ALTER TABLE "TBL_TOKEN" ADD CONSTRAINT "TBL_TOKEN_PK" PRIMARY KEY ("N_REFRESHTOKENID")USING INDEX "TBL_TOKEN_PK"  ENABLE;


CREATE TABLE "TBL_APPROVAL_FLOW"(
"N_APPROVAL_ID" NUMBER GENERATED ALWAYS AS IDENTITY,
"N_FLOW_TYPE_ID" NUMBER, 	
"N_FLOW_TYPE_SUB_ID" NUMBER, 	
"S_FLOW_TYPE" VARCHAR2(255) NOT NULL, 	
"S_ACTION" VARCHAR2(50 CHAR) NOT NULL, 
"S_MAKER" VARCHAR2(50 CHAR) NOT NULL,
"S_CHECKER" VARCHAR2(50 CHAR) NOT NULL, 	
"S_MAKER_COMMENTS" VARCHAR2(255 CHAR), 	
"S_CHECKER_COMMENTS" VARCHAR2(255 CHAR),
"S_REALM" VARCHAR2(255 CHAR) NOT NULL,
"S_DOCUMENT_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
"B_DOCUMENT" BLOB,
"S_CREATEDBY" VARCHAR2(50 CHAR), 
"DT_CREATEDDATE" DATE, 	
"S_UPDATEDBY" VARCHAR2(50 CHAR), 	
"DT_UPDATEDDATE" DATE
);

CREATE UNIQUE INDEX "TBL_APPROVAL_FLOW_PK" ON "TBL_APPROVAL_FLOW" ("N_APPROVAL_ID");
ALTER TABLE "TBL_APPROVAL_FLOW" ADD CONSTRAINT "TBL_APPROVAL_FLOW_PK" PRIMARY KEY ("N_APPROVAL_ID")  USING INDEX "TBL_APPROVAL_FLOW_PK"  ENABLE;